export const darkTheme = {
  mode: "dark",
  PRIMARY_BACKGROUND_COLOR: "#121212",
  PRIMARY_LINEAR_GRADIENT: ["#121212", "#121212"],
  SECOND_BACKGROUND_COLOR: "#7FC4DC",
  PRIMARY_TEXT_COLOR: "#ffffff",
  SECOND_TEXT_COLOR: "#B6B6B6",
  PRIMARY_BUTTON_COLOR: "#3B3DBF",
  PRIMARY_BUTTON_TEXT_COLOR: "#FFFFFF",
  BORDER_COLOR: "#c8c8c8",
  BORDER_BUTTON_BOTTOM_BAR: "#000000",
  STATUS_BAR_STYLE: "light-conent",
};

export const lightTheme = {
  mode: "light",
  PRIMARY_BACKGROUND_COLOR: "#EFF1F5",
  PRIMARY_LINEAR_GRADIENT: ["#ffffff", "#EFF1F5"],
  SECOND_BACKGROUND_COLOR: "#7FC4DC",
  PRIMARY_TEXT_COLOR: "#2F2F2F",
  SECOND_TEXT_COLOR: "#B6B6B6",
  PRIMARY_BUTTON_COLOR: "#3B3DBF",
  PRIMARY_BUTTON_TEXT_COLOR: "#FFFFFF",
  BORDER_COLOR: "#c8c8c8",
  BORDER_BUTTON_BOTTOM_BAR: "#eff1f5",
  STATUS_BAR_STYLE: "light-conent",
};
